### PR TITLE
adds records api-calls to manage and use auth on collections

### PR DESCRIPTION
**Pull request by bbuehrig**
I tried to implement the functions from the js-sdk record-service.

### CODE REVIEW

**Comment by pluja** [comment]
@bbuehrig I removed the 0.0.61 release. Could you add a little sample usage in the README.md file for your implementation?

**Comment by bbuehrig** [comment]
Done! :)

**Comment by bbuehrig** [comment]
@pluja now it's ready. Workflows are green... I extend the Readme  with a simple example. Ready for review and hopefully merging! :)

**Comment by pluja** [comment]
Awesome, seems all good!

**Pull request merged**
